"use client";

import { useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, ArrowRight, Check, Gamepad2, LockKeyhole, Mail, RefreshCcw, ShieldCheck, Smartphone, TriangleAlert } from "lucide-react";
import { Button, Input, ThemeSwitcher, cn } from "@game-aggregator/ui-web";
import { forgotPasswordSchema, loginSchema, mfaSchema, registerSchema, resetPasswordSchema, type ForgotPasswordInput, type LoginInput, type MfaInput, type RegisterInput, type ResetPasswordInput } from "@game-aggregator/validation";

export type AuthScreenMode = "login" | "register" | "forgot-password" | "reset-password" | "mfa" | "session-expired" | "tenant-selector" | "unauthorized" | "account-locked";
export interface TenantOption { id: string; name: string; role: string; initials: string; }
export interface AuthScreenProps { mode: AuthScreenMode; portalName: string; portalLabel: string; apiBaseUrl?: string; tenants?: TenantOption[]; }

const defaultTenants: TenantOption[] = [{ id: "northwind", name: "Northwind Games", role: "Studio administrator", initials: "NG" }, { id: "atlas", name: "Atlas Publishing", role: "Release manager", initials: "AP" }, { id: "sandbox", name: "Personal Sandbox", role: "Developer", initials: "PS" }];

export function AuthScreen({ mode, portalName, portalLabel, apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL ?? "/backend", tenants = defaultTenants }: AuthScreenProps) {
  return <AuthCanvas portalName={portalName} portalLabel={portalLabel}>{mode === "login" && <LoginForm apiBaseUrl={apiBaseUrl}/>} {mode === "register" && <RegisterForm apiBaseUrl={apiBaseUrl}/>} {mode === "forgot-password" && <ForgotPasswordForm apiBaseUrl={apiBaseUrl}/>} {mode === "reset-password" && <ResetPasswordForm apiBaseUrl={apiBaseUrl}/>} {mode === "mfa" && <MfaForm/>} {mode === "session-expired" && <StatusCard icon={<RefreshCcw/>} eyebrow="Session expired" title="Welcome back" description="Your session ended to keep your account secure. Sign in again to continue where you left off." action="Sign in again" href="/login"/>} {mode === "tenant-selector" && <TenantSelector tenants={tenants}/>} {mode === "unauthorized" && <StatusCard icon={<LockKeyhole/>} eyebrow="Access denied" title="You cannot view this page" description="Your current role does not include the required permission. Switch tenant or ask an administrator for access." action="Switch tenant" href="/tenant-selector" secondary="Return to dashboard"/>} {mode === "account-locked" && <StatusCard icon={<TriangleAlert/>} eyebrow="Account protected" title="Your account is temporarily locked" description="We detected too many unsuccessful sign-in attempts. Try again in 14 minutes or reset your password now." action="Reset password" href="/forgot-password" secondary="Contact support" tone="danger"/>}</AuthCanvas>;
}

function AuthCanvas({ portalName, portalLabel, children }: { portalName: string; portalLabel: string; children: ReactNode }) {
  return <main className="min-h-dvh bg-[var(--ga-background)] text-[var(--ga-foreground)] lg:grid lg:grid-cols-[minmax(22rem,0.86fr)_minmax(32rem,1.14fr)]">
    <section className="relative hidden overflow-hidden bg-[#071a17] p-10 text-white lg:flex lg:flex-col lg:justify-between xl:p-14">
      <div className="absolute inset-0 opacity-80 [background:radial-gradient(circle_at_15%_15%,rgba(42,174,136,.34),transparent_34%),radial-gradient(circle_at_90%_75%,rgba(57,112,210,.25),transparent_38%)]"/>
      <div className="relative flex items-center gap-3"><BrandMark/><div><div className="font-semibold tracking-tight">{portalName}</div><div className="text-xs text-white/55">{portalLabel}</div></div></div>
      <div className="relative max-w-lg"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs text-white/75"><ShieldCheck className="size-3.5 text-emerald-300"/>Enterprise identity and access</div><h1 className="text-4xl font-semibold leading-[1.12] tracking-[-0.035em] xl:text-5xl">One secure workspace for every game operation.</h1><p className="mt-5 max-w-md text-sm leading-6 text-white/60 xl:text-base">Move confidently between studios, clients, releases, and environments with tenant-aware permissions.</p></div>
      <div className="relative grid gap-3 text-sm text-white/65"><TrustLine text="OAuth2 resource protection"/><TrustLine text="Tenant-isolated permissions"/><TrustLine text="Audited sessions and security events"/></div>
    </section>
    <section className="relative flex min-h-dvh flex-col"><ThemeSwitcher className="absolute right-5 top-5 z-20 hidden lg:flex"/>
      <div className="flex items-center justify-between border-b border-[var(--ga-border)] bg-[var(--ga-surface)] px-5 py-4 lg:hidden"><div className="flex items-center gap-2.5"><BrandMark compact/><div><div className="text-sm font-semibold">{portalName}</div><div className="text-[11px] text-[var(--ga-muted-foreground)]">{portalLabel}</div></div></div><ThemeSwitcher/><ShieldCheck className="hidden size-5 text-[var(--ga-primary)] sm:block"/></div>
      <div className="flex flex-1 items-center justify-center px-5 py-10 sm:px-8 lg:px-12"><div className="w-full max-w-[27rem]">{children}</div></div>
      <footer className="flex flex-wrap items-center justify-center gap-x-5 gap-y-2 px-5 pb-6 text-xs text-[var(--ga-muted-foreground)]"><a href="#">Privacy</a><a href="#">Security</a><a href="#">Help center</a><span>&copy; 2026 Game Aggregator</span></footer>
    </section>
  </main>;
}
function BrandMark({ compact=false }: { compact?: boolean }) { return <span className={cn("grid place-items-center rounded-xl bg-emerald-400 text-[#06231d] shadow-lg shadow-emerald-950/20", compact?"size-9":"size-11")}><Gamepad2 className={compact?"size-5":"size-6"}/></span>; }
function TrustLine({ text }: { text:string }) { return <div className="flex items-center gap-3"><span className="grid size-5 place-items-center rounded-full bg-emerald-300/15"><Check className="size-3 text-emerald-300"/></span>{text}</div>; }
function Heading({ eyebrow, title, description }: { eyebrow:string; title:string; description:string }) { return <div className="mb-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--ga-primary)]">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.025em] sm:text-3xl">{title}</h2><p className="mt-2 text-sm leading-6 text-[var(--ga-muted-foreground)]">{description}</p></div>; }
function SubmitButton({ busy, children }: { busy:boolean; children:ReactNode }) { return <Button type="submit" size="lg" className="mt-1 w-full" disabled={busy}>{busy?<><RefreshCcw className="size-4 animate-spin"/>Please wait</>:<>{children}<ArrowRight className="size-4"/></>}</Button>; }

function LoginForm({ apiBaseUrl }: { apiBaseUrl:string }) {
 const [serverError,setServerError]=useState(""); const [busy,setBusy]=useState(false); const {register,handleSubmit,formState:{errors}}=useForm<LoginInput>({resolver:zodResolver(loginSchema)});
 const submit=handleSubmit(async values=>{setBusy(true);setServerError("");try{const response=await fetch(`${apiBaseUrl}/auth/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload?.error?.message??"Sign in failed");sessionStorage.setItem("ga_access_token",payload.data.accessToken);sessionStorage.setItem("ga_refresh_token",payload.data.refreshToken);window.location.assign("/");}catch(error){setServerError(error instanceof Error?error.message:"Unable to sign in");}finally{setBusy(false);}});
 return <><Heading eyebrow="Secure sign in" title="Welcome back" description="Enter your work account to continue to your tenant workspace."/><form onSubmit={submit} className="grid gap-4"><Input label="Work email" type="email" autoComplete="email" placeholder="you@company.com" error={errors.email?.message} {...register("email")}/><div><div className="mb-1.5 flex items-center justify-between"><label htmlFor="login-password" className="text-sm font-medium">Password</label><a className="text-xs font-medium text-[var(--ga-primary)] hover:underline" href="/forgot-password">Forgot password?</a></div><Input id="login-password" type="password" autoComplete="current-password" placeholder="Enter your password" error={errors.password?.message} {...register("password")}/></div>{serverError&&<InlineError>{serverError}</InlineError>}<SubmitButton busy={busy}>Sign in</SubmitButton></form><div className="mt-6 grid gap-3 text-center text-xs text-[var(--ga-muted-foreground)]"><p>Protected by rate limiting, account lockout, and session monitoring.</p><p>Have an invitation? <a href="/register" className="font-semibold text-[var(--ga-primary)] hover:underline">Create your account</a></p></div></>;
}
function RegisterForm({ apiBaseUrl }: { apiBaseUrl:string }) {
 const [done,setDone]=useState(false),[busy,setBusy]=useState(false),[serverError,setServerError]=useState("");
 const {register,handleSubmit,formState:{errors}}=useForm<RegisterInput>({resolver:zodResolver(registerSchema)});
 const submit=handleSubmit(async values=>{setBusy(true);setServerError("");try{const response=await fetch(`${apiBaseUrl}/auth/register`,{method:"POST",headers:{"Content-Type":"application/json","X-Internal-Registration-Key":values.invitationKey},body:JSON.stringify({displayName:values.displayName,email:values.email,password:values.password})});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload?.error?.message??"Registration failed");setDone(true);}catch(error){setServerError(error instanceof Error?error.message:"Unable to create account");}finally{setBusy(false);}});
 if(done)return <StatusCard icon={<Check/>} eyebrow="Account created" title="Your account is ready" description="Sign in to choose your tenant workspace and continue." action="Continue to sign in" href="/login"/>;
 return <><BackLink/><Heading eyebrow="Invitation-only registration" title="Create your work account" description="Use the invitation key supplied by your platform administrator."/><form onSubmit={submit} className="grid gap-4"><Input label="Display name" autoComplete="name" placeholder="Alex Morgan" error={errors.displayName?.message} {...register("displayName")}/><Input label="Work email" type="email" autoComplete="email" placeholder="you@company.com" error={errors.email?.message} {...register("email")}/><Input label="Password" type="password" autoComplete="new-password" placeholder="At least 12 characters" error={errors.password?.message} {...register("password")}/><Input label="Invitation key" type="password" autoComplete="off" placeholder="Provided by your administrator" error={errors.invitationKey?.message} {...register("invitationKey")}/>{serverError&&<InlineError>{serverError}</InlineError>}<SubmitButton busy={busy}>Create account</SubmitButton></form><p className="mt-5 text-center text-xs text-[var(--ga-muted-foreground)]">Registration is restricted and audited. Contact your administrator if you do not have an invitation.</p></>;
}
function ForgotPasswordForm({ apiBaseUrl }: { apiBaseUrl:string }) { const [sent,setSent]=useState(false),[busy,setBusy]=useState(false);const {register,handleSubmit,formState:{errors}}=useForm<ForgotPasswordInput>({resolver:zodResolver(forgotPasswordSchema)});const submit=handleSubmit(async values=>{setBusy(true);try{await fetch(`${apiBaseUrl}/auth/forgot-password`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});}finally{setSent(true);setBusy(false);}});if(sent)return <StatusCard icon={<Mail/>} eyebrow="Check your inbox" title="Reset link requested" description="If an account matches that email, password reset instructions are on the way." action="Back to sign in" href="/login"/>;return <><BackLink/><Heading eyebrow="Password recovery" title="Reset your password" description="Enter your work email and we will send secure reset instructions."/><form onSubmit={submit} className="grid gap-4"><Input label="Work email" type="email" placeholder="you@company.com" error={errors.email?.message} {...register("email")}/><SubmitButton busy={busy}>Send reset link</SubmitButton></form></>; }
function ResetPasswordForm({ apiBaseUrl }: { apiBaseUrl:string }) { const [done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const {register,handleSubmit,formState:{errors}}=useForm<ResetPasswordInput>({resolver:zodResolver(resetPasswordSchema)});const submit=handleSubmit(async values=>{setBusy(true);setError("");const token=new URLSearchParams(window.location.search).get("token")??"";try{const response=await fetch(`${apiBaseUrl}/auth/reset-password`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,newPassword:values.password})});if(!response.ok)throw new Error("This reset link is invalid or has expired.");setDone(true);}catch(e){setError(e instanceof Error?e.message:"Unable to reset password");}finally{setBusy(false);}});if(done)return <StatusCard icon={<Check/>} eyebrow="Password updated" title="You are ready to sign in" description="Your password has been changed and other active sessions may be revoked." action="Continue to sign in" href="/login"/>;return <><BackLink/><Heading eyebrow="Choose a new password" title="Create a strong password" description="Use at least 12 characters with uppercase, lowercase, and a number."/><form onSubmit={submit} className="grid gap-4"><Input label="New password" type="password" autoComplete="new-password" error={errors.password?.message} {...register("password")}/><Input label="Confirm password" type="password" autoComplete="new-password" error={errors.confirmPassword?.message} {...register("confirmPassword")}/>{error&&<InlineError>{error}</InlineError>}<SubmitButton busy={busy}>Update password</SubmitButton></form></>; }
function MfaForm() { const [busy,setBusy]=useState(false);const {register,handleSubmit,formState:{errors}}=useForm<MfaInput>({resolver:zodResolver(mfaSchema)});const submit=handleSubmit(async()=>{setBusy(true);await new Promise(resolve=>setTimeout(resolve,500));window.location.assign("/");});return <><Heading eyebrow="Two-step verification" title="Confirm it is you" description="Enter the 6-digit code from your authenticator app."/><div className="mb-5 flex items-center gap-3 rounded-[var(--ga-radius-lg)] border border-[var(--ga-border)] bg-[var(--ga-surface-muted)] p-4"><span className="grid size-10 place-items-center rounded-full bg-[var(--ga-surface)]"><Smartphone className="size-5"/></span><div><p className="text-sm font-medium">Authenticator app</p><p className="text-xs text-[var(--ga-muted-foreground)]">Code refreshes every 30 seconds</p></div></div><form onSubmit={submit} className="grid gap-4"><Input label="Verification code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} className="h-14 text-center font-mono text-2xl tracking-[.4em]" error={errors.code?.message} {...register("code")}/><SubmitButton busy={busy}>Verify and continue</SubmitButton></form><div className="mt-5 text-center"><button className="text-xs font-medium text-[var(--ga-primary)]">Use a recovery code</button></div></>; }
function TenantSelector({ tenants }: { tenants:TenantOption[] }) { return <><Heading eyebrow="Choose workspace" title="Where are you working today?" description="Your data and permissions change with the selected tenant."/><div className="grid gap-3">{tenants.map((tenant,index)=><a key={tenant.id} href="/" className="group flex items-center gap-3 rounded-[var(--ga-radius-lg)] border border-[var(--ga-border)] bg-[var(--ga-surface)] p-3.5 transition hover:-translate-y-0.5 hover:border-[var(--ga-ring)] hover:shadow-[var(--ga-shadow-sm)]"><span className={cn("grid size-11 shrink-0 place-items-center rounded-lg text-sm font-semibold",index===0?"bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200":index===1?"bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-200":"bg-violet-100 text-violet-800 dark:bg-violet-950 dark:text-violet-200")}>{tenant.initials}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{tenant.name}</span><span className="block truncate text-xs text-[var(--ga-muted-foreground)]">{tenant.role}</span></span><ArrowRight className="size-4 text-[var(--ga-muted-foreground)] transition group-hover:translate-x-0.5"/></a>)}</div><a href="/login" className="mt-6 flex items-center justify-center gap-2 text-xs text-[var(--ga-muted-foreground)]"><ArrowLeft className="size-3.5"/>Sign in with another account</a></>; }
function StatusCard({ icon,eyebrow,title,description,action,href,secondary,tone="normal" }: {icon:ReactNode;eyebrow:string;title:string;description:string;action:string;href:string;secondary?:string;tone?:"normal"|"danger"}) { return <div className="text-center"><span className={cn("mx-auto grid size-16 place-items-center rounded-2xl",tone==="danger"?"bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-200":"bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200","[&_svg]:size-7")}>{icon}</span><div className="mt-6"><p className={cn("text-xs font-semibold uppercase tracking-[.16em]",tone==="danger"?"text-red-700":"text-[var(--ga-primary)]")}>{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[var(--ga-muted-foreground)]">{description}</p></div><Button size="lg" className="mt-7 w-full" onClick={()=>window.location.assign(href)}>{action}<ArrowRight className="size-4"/></Button>{secondary&&<button onClick={()=>history.back()} className="mt-4 text-sm text-[var(--ga-muted-foreground)] hover:text-[var(--ga-foreground)]">{secondary}</button>}</div>; }
function InlineError({children}:{children:ReactNode}) { return <div role="alert" className="flex items-start gap-2 rounded-md border border-red-200 bg-red-50 p-3 text-xs text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-200"><TriangleAlert className="mt-0.5 size-4 shrink-0"/>{children}</div>; }
function BackLink() { return <a href="/login" className="mb-6 inline-flex items-center gap-2 text-xs font-medium text-[var(--ga-muted-foreground)] hover:text-[var(--ga-foreground)]"><ArrowLeft className="size-3.5"/>Back to sign in</a>; }
