"use client";

import { adminApi, managementEndpoints, type Entity } from "@game-aggregator/api-client";
import { Badge, Button, EmptyState, Input, Modal, Skeleton, Table, Tabs } from "@game-aggregator/ui-web";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BarChart3, Building2, Gamepad2, KeyRound, Plus, RefreshCw, Search, Server, Users } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";

const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 15_000, retry: 1, refetchOnWindowFocus: false } } });
type Section = "overview"|"organizations"|"games"|"api-keys"|"operations"|"finance";
type DatasetKey = "studios"|"publishers"|"clients"|"games"|"versions"|"builds"|"releases"|"deployments"|"apiKeys"|"contracts"|"revenueRules"|"ledger"|"invoices"|"incidents"|"auditLogs";
const sections = [{id:"overview",label:"Dashboard"},{id:"organizations",label:"Organizations"},{id:"games",label:"Games"},{id:"api-keys",label:"API keys"},{id:"operations",label:"Health & incidents"},{id:"finance",label:"Revenue & contracts"}];
const datasetBySection: Record<Exclude<Section,"overview">,DatasetKey[]> = { organizations:["studios","publishers","clients"], games:["games","versions","builds","releases"], "api-keys":["apiKeys"], operations:["deployments","incidents","auditLogs"], finance:["contracts","revenueRules","ledger","invoices"] };
const labels: Record<DatasetKey,string> = {studios:"Studios",publishers:"Publishers",clients:"Clients",games:"Games",versions:"Versions",builds:"Builds",releases:"Releases",deployments:"Deployments",apiKeys:"API keys",contracts:"Contracts",revenueRules:"Revenue rules",ledger:"Transaction ledger",invoices:"Invoices",incidents:"Incidents",auditLogs:"Audit log"};

export function PlatformAdminConsole(){return <QueryClientProvider client={queryClient}><Console/></QueryClientProvider>}
function Console(){
 const [section,setSection]=useState<Section>("overview"); const [search,setSearch]=useState(""); const [create,setCreate]=useState<DatasetKey|null>(null); useEffect(()=>{const sync=()=>{const value=window.location.hash.slice(1) as Section;if(sections.some(item=>item.id===value))setSection(value)};sync();window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync)},[]);
 const queries=useAdminQueries(); const data=Object.fromEntries(Object.entries(queries).map(([key,q])=>[key,q.data??[]])) as Record<DatasetKey,Entity[]>;
 const loading=Object.values(queries).some(q=>q.isLoading); const errors=Object.values(queries).filter(q=>q.isError).length;
 const refresh=()=>Object.values(queries).forEach(q=>q.refetch());
 const active=section==="overview"?[]:datasetBySection[section];
 return <div className="grid gap-6">
  <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--ga-primary)]">Platform control plane</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Platform administration</h1><p className="mt-2 max-w-3xl text-sm text-[var(--ga-muted-foreground)]">Live operational data from the platform microservices. Mutations are persisted by Flyway-managed MySQL schemas.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={refresh}><RefreshCw className="size-4"/>Refresh data</Button>{section!=="overview"&&section!=="operations"&&<Button onClick={()=>setCreate(active[0])}><Plus className="size-4"/>Create {labels[active[0]].toLowerCase()}</Button>}</div></header>
  <div className="overflow-x-auto"><Tabs tabs={sections} value={section} onValueChange={v=>{setSection(v as Section);history.replaceState(null,"",`#${v}`)}}/></div>
  {section==="overview"?<Overview data={data} loading={loading} errors={errors}/>:<section className="grid gap-4"><div className="relative max-w-md"><Search className="pointer-events-none absolute left-3 top-2.5 size-4 text-[var(--ga-muted-foreground)]"/><Input aria-label="Search records" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records..." className="pl-9"/></div>{active.map(key=><DataPanel key={key} datasetKey={key} rows={data[key]} loading={queries[key].isLoading} error={queries[key].error} search={search} onCreate={key==="auditLogs"?undefined:()=>setCreate(key)}/>)}</section>}
  <CreateDialog kind={create} close={()=>setCreate(null)}/>
 </div>
}
function useAdminQueries(){return {
 studios:useQuery({queryKey:["admin","studios"],queryFn:adminApi.list.studios}), publishers:useQuery({queryKey:["admin","publishers"],queryFn:adminApi.list.publishers}), clients:useQuery({queryKey:["admin","clients"],queryFn:adminApi.list.clients}), games:useQuery({queryKey:["admin","games"],queryFn:adminApi.list.games}), versions:useQuery({queryKey:["admin","versions"],queryFn:adminApi.list.versions}), builds:useQuery({queryKey:["admin","builds"],queryFn:adminApi.list.builds}), releases:useQuery({queryKey:["admin","releases"],queryFn:adminApi.list.releases}), deployments:useQuery({queryKey:["admin","deployments"],queryFn:adminApi.list.deployments}), apiKeys:useQuery({queryKey:["admin","apiKeys"],queryFn:adminApi.list.apiKeys}), contracts:useQuery({queryKey:["admin","contracts"],queryFn:adminApi.list.contracts}), revenueRules:useQuery({queryKey:["admin","revenueRules"],queryFn:adminApi.list.revenueRules}), ledger:useQuery({queryKey:["admin","ledger"],queryFn:adminApi.list.ledger}), invoices:useQuery({queryKey:["admin","invoices"],queryFn:adminApi.list.invoices}), incidents:useQuery({queryKey:["admin","incidents"],queryFn:adminApi.list.incidents}), auditLogs:useQuery({queryKey:["admin","auditLogs"],queryFn:adminApi.list.auditLogs})};}
function Overview({data,loading,errors}:{data:Record<DatasetKey,Entity[]>;loading:boolean;errors:number}){
 const metrics=[{label:"Total games",value:data.games.length,icon:<Gamepad2/>},{label:"Active studios",value:data.studios.filter(x=>x.status==="ACTIVE").length,icon:<Building2/>},{label:"Active clients",value:data.clients.length,icon:<Users/>},{label:"API keys",value:data.apiKeys.filter(x=>x.status!=="REVOKED").length,icon:<KeyRound/>},{label:"Open incidents",value:data.incidents.filter(x=>x.status!=="RESOLVED").length,icon:<AlertTriangle/>},{label:"Current deployments",value:data.deployments.filter(x=>!["SUCCEEDED","FAILED","CANCELLED","ROLLED_BACK"].includes(String(x.status))).length,icon:<Server/>}];
 return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{metrics.map(m=><article key={m.label} className="rounded-2xl border border-[var(--ga-border)] bg-[var(--ga-surface)] p-4 shadow-sm"><div className="flex items-center justify-between text-[var(--ga-muted-foreground)]"><span className="text-xs font-medium">{m.label}</span><span className="[&_svg]:size-4">{m.icon}</span></div>{loading?<Skeleton className="mt-4 h-8 w-16"/>:<p className="mt-3 text-3xl font-semibold tabular-nums">{m.value}</p>}</article>)}</div><div className="grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><article className="rounded-2xl border border-[var(--ga-border)] bg-[var(--ga-surface)] p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Platform footprint</h2><p className="text-sm text-[var(--ga-muted-foreground)]">Records persisted across domain services</p></div><BarChart3 className="size-5 text-[var(--ga-primary)]"/></div><div className="mt-6 grid h-56 grid-cols-5 items-end gap-3">{(["studios","publishers","clients","games","apiKeys"] as DatasetKey[]).map((key,i)=><div key={key} className="grid h-full content-end gap-2"><div className="mx-auto w-full max-w-14 rounded-t-lg bg-[var(--ga-primary)]/80" style={{height:`${Math.max(10,Math.min(100,data[key].length*12+18+i*5))}%`}}/><p className="truncate text-center text-[10px] text-[var(--ga-muted-foreground)]">{labels[key]}</p></div>)}</div></article><article className="rounded-2xl border border-[var(--ga-border)] bg-[var(--ga-surface)] p-5"><h2 className="font-semibold">API health</h2><div className="mt-5 grid gap-3"><Health label="Management services" ok={errors===0}/><Health label="MySQL persistence" ok={errors===0}/><Health label="Authenticated proxy" ok={errors===0}/></div><p className="mt-5 text-xs text-[var(--ga-muted-foreground)]">{errors?`${errors} service request(s) need attention.`:"All queried APIs are responding normally."}</p></article></div></>
}
function Health({label,ok}:{label:string;ok:boolean}){return <div className="flex items-center justify-between rounded-xl bg-[var(--ga-surface-muted)] p-3"><span className="flex items-center gap-2 text-sm"><Server className="size-4"/>{label}</span><Badge tone={ok?"success":"danger"}>{ok?"Healthy":"Unavailable"}</Badge></div>}
function DataPanel({datasetKey,rows,loading,error,search,onCreate}:{datasetKey:DatasetKey;rows:Entity[];loading:boolean;error:Error|null;search:string;onCreate?:()=>void}){
 const filtered=useMemo(()=>rows.filter(row=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),[rows,search]);
 return <article className="overflow-hidden rounded-2xl border border-[var(--ga-border)] bg-[var(--ga-surface)]"><header className="flex items-center justify-between border-b border-[var(--ga-border)] p-4"><div><h2 className="font-semibold">{labels[datasetKey]}</h2><p className="text-xs text-[var(--ga-muted-foreground)]">{rows.length} persisted records</p></div>{onCreate&&<Button size="sm" variant="outline" onClick={onCreate}><Plus className="size-3.5"/>Add</Button>}</header>{loading?<div className="grid gap-3 p-5"><Skeleton/><Skeleton/><Skeleton/></div>:error?<EmptyState icon={<AlertTriangle/>} title={`Could not load ${labels[datasetKey]}`} description={error.message}/>:filtered.length===0?<EmptyState title={`No ${labels[datasetKey].toLowerCase()} found`} description="Create the first record or change your search." action={onCreate?<Button size="sm" onClick={onCreate}>Create record</Button>:undefined}/>:<Table><thead><tr><th>Name</th><th>Status / type</th><th>Identifier</th><th>Updated</th><th className="text-right">Actions</th></tr></thead><tbody>{filtered.slice(0,50).map(row=><tr key={row.id}><td className="font-medium">{String(row.name??row.title??row.incidentNumber??row.invoiceNumber??row.code??"Record")}</td><td><Badge tone={tone(String(row.status??row.severity??row.action??"ACTIVE"))}>{String(row.status??row.severity??row.action??row.visibility??"Active")}</Badge></td><td className="max-w-48 truncate font-mono text-xs text-[var(--ga-muted-foreground)]">{row.id}</td><td className="whitespace-nowrap text-[var(--ga-muted-foreground)]">{formatDate(row.createdAt??row.occurredAt)}</td><td><RowActions kind={datasetKey} row={row}/></td></tr>)}</tbody></Table>}</article>
}
function RowActions({kind,row}:{kind:DatasetKey;row:Entity}){const qc=useQueryClient();const mutation=useMutation({mutationFn:async({path,method}:{path:string;method:"action"|"remove"}):Promise<unknown>=>method==="remove"?adminApi.remove(path):adminApi.action(path),onSuccess:()=>qc.invalidateQueries({queryKey:["admin"]})});let actions:Array<{label:string;path:string;method:"action"|"remove"}>=[];if(kind==="games"&&row.status!=="ARCHIVED")actions=[{label:"Archive",path:`${managementEndpoints.games}/${row.id}/archive`,method:"action"}];if(kind==="apiKeys")actions=[{label:"Rotate",path:`${managementEndpoints.apiKeys}/${row.id}/rotate`,method:"action"},{label:"Revoke",path:`${managementEndpoints.apiKeys}/${row.id}/revoke`,method:"action"},{label:"Delete",path:`${managementEndpoints.apiKeys}/${row.id}`,method:"remove"}];if(kind==="studios"||kind==="publishers")actions=[{label:"Delete",path:`${kind==="studios"?managementEndpoints.studios:managementEndpoints.publishers}/${row.id}`,method:"remove"}];if(!actions.length)return <span className="block text-right text-xs text-[var(--ga-muted-foreground)]">View only</span>;return <div className="flex justify-end gap-1">{actions.map(action=><Button key={action.label} size="sm" variant={action.label==="Delete"||action.label==="Revoke"?"danger":"ghost"} disabled={mutation.isPending} onClick={()=>mutation.mutate(action)}>{action.label}</Button>)}</div>}function tone(value:string):"neutral"|"success"|"warning"|"danger"|"info"{if(/ACTIVE|PAID|RESOLVED|APPROVED|SUCCEEDED/i.test(value))return"success";if(/FAILED|REVOKED|SEV1|SEV2|SUSPENDED/i.test(value))return"danger";if(/PENDING|OPEN|DRAFT|SEV3/i.test(value))return"warning";return"info"}
function formatDate(value:unknown){if(!value)return"--";const date=new Date(String(value));return Number.isNaN(date.valueOf())?String(value):new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(date)}
const forms:Partial<Record<DatasetKey,{path:string;fields:Array<{name:string;label:string;type?:string;placeholder?:string}>}>>={
 studios:{path:managementEndpoints.studios,fields:[{name:"tenantId",label:"Tenant ID"},{name:"slug",label:"Slug"},{name:"name",label:"Studio name"},{name:"ownerUserId",label:"Owner user ID"}]},
 publishers:{path:managementEndpoints.publishers,fields:[{name:"tenantId",label:"Tenant ID"},{name:"slug",label:"Slug"},{name:"name",label:"Publisher name"},{name:"ownerUserId",label:"Owner user ID"}]},
 clients:{path:`${managementEndpoints.clients}/organizations`,fields:[{name:"tenantId",label:"Tenant ID"},{name:"slug",label:"Slug"},{name:"name",label:"Client organization"}]},
 games:{path:managementEndpoints.games,fields:[{name:"studioId",label:"Studio ID"},{name:"publisherId",label:"Publisher ID (optional)"},{name:"slug",label:"Slug"},{name:"title",label:"Game title"},{name:"ageRating",label:"Age rating"}]},
 apiKeys:{path:managementEndpoints.apiKeys,fields:[{name:"tenantId",label:"Tenant ID"},{name:"clientId",label:"Client ID"},{name:"environmentId",label:"Environment ID"},{name:"scopes",label:"Scopes (comma separated)",placeholder:"game:read,release:read"},{name:"quota",label:"Monthly quota",type:"number"},{name:"expiresAt",label:"Expiration (optional)",type:"datetime-local"},{name:"ipAllowlist",label:"IP allowlist (optional)",placeholder:"203.0.113.10"}]},
 contracts:{path:managementEndpoints.contracts,fields:[{name:"contractNumber",label:"Contract number"},{name:"createdBy",label:"Created by user ID"}]},
 revenueRules:{path:managementEndpoints.revenueRules,fields:[{name:"contractId",label:"Contract ID"},{name:"gameId",label:"Game ID"},{name:"name",label:"Revenue rule name"}]},
 invoices:{path:`${managementEndpoints.billing}/invoices`,fields:[{name:"invoiceNumber",label:"Invoice number"},{name:"clientId",label:"Client ID"},{name:"cycleFrom",label:"Cycle from",type:"date"},{name:"cycleTo",label:"Cycle to",type:"date"},{name:"total",label:"Total",type:"number"},{name:"currency",label:"Currency",placeholder:"USD"}]},
 incidents:{path:managementEndpoints.incidents,fields:[{name:"incidentNumber",label:"Incident number"},{name:"title",label:"Title"},{name:"description",label:"Description"},{name:"actorId",label:"Actor user ID"}]},
};
function CreateDialog({kind,close}:{kind:DatasetKey|null;close:()=>void}){
 const qc=useQueryClient(); const config=kind?forms[kind]:undefined; const [error,setError]=useState(""); const [issued,setIssued]=useState("");
 const mutation=useMutation({mutationFn:({path,payload}:{path:string;payload:Record<string,unknown>})=>adminApi.create(path,payload),onSuccess:data=>{qc.invalidateQueries({queryKey:["admin"]});if(typeof data.apiKey==="string")setIssued(data.apiKey);else close()},onError:e=>setError(e.message)});
 if(!kind||!config)return null;
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const entries=Array.from(new FormData(event.currentTarget).entries()).filter(([,value])=>String(value).trim()!=="");let payload:Record<string,unknown>=Object.fromEntries(entries);if(kind==="games")payload={...payload,metadata:"{}",visibility:"PRIVATE"};if(kind==="apiKeys")payload={...payload,scopes:String(payload.scopes).split(",").map(v=>v.trim()).filter(Boolean),ipAllowlist:String(payload.ipAllowlist??"").split(",").map(v=>v.trim()).filter(Boolean),quota:Number(payload.quota),expiresAt:payload.expiresAt?new Date(String(payload.expiresAt)).toISOString():null};if(kind==="invoices")payload={...payload,total:Number(payload.total)};if(kind==="incidents")payload={...payload,severity:"SEV3",affectedServices:["platform"],assigneeId:null,relatedDeploymentId:null};mutation.mutate({path:config!.path,payload})}
 function finish(){setIssued("");close()}
 return <Modal open title={issued?"API key created":`Create ${labels[kind]}`} onClose={issued?finish:close}>{issued?<div className="grid gap-4"><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-800 dark:bg-amber-950"><p className="text-sm font-semibold text-amber-900 dark:text-amber-100">Copy this secret now</p><p className="mt-1 text-xs text-amber-800 dark:text-amber-200">For security, the raw key is never stored in MySQL and cannot be displayed again.</p><code className="mt-4 block break-all rounded-lg bg-white p-3 text-xs text-slate-900 dark:bg-slate-900 dark:text-slate-100">{issued}</code></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>navigator.clipboard.writeText(issued)}>Copy key</Button><Button onClick={finish}>Done</Button></div></div>:<form className="grid gap-4" onSubmit={submit}>{config.fields.map(field=><Input key={field.name} name={field.name} type={field.type} label={field.label} placeholder={field.placeholder} required={!field.label.includes("optional")}/>)}{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950 dark:text-red-200">{error}</p>}<div className="flex justify-end gap-2"><Button variant="ghost" onClick={close}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?"Saving to database...":"Create record"}</Button></div></form>}</Modal>
}