CREATE DATABASE IF NOT EXISTS auth_service;
CREATE DATABASE IF NOT EXISTS tenant_service;
CREATE DATABASE IF NOT EXISTS authorization_service;
CREATE DATABASE IF NOT EXISTS studio_service;
CREATE DATABASE IF NOT EXISTS publisher_service;
CREATE DATABASE IF NOT EXISTS client_service;
GRANT ALL PRIVILEGES ON auth_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON tenant_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON authorization_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON studio_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON publisher_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON client_service.* TO 'game_app'@'%';
CREATE DATABASE IF NOT EXISTS game_service;
CREATE DATABASE IF NOT EXISTS game_media_service;
CREATE DATABASE IF NOT EXISTS entitlement_service;
GRANT ALL PRIVILEGES ON game_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON game_media_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON entitlement_service.* TO 'game_app'@'%';
CREATE DATABASE IF NOT EXISTS api_key_service;
GRANT ALL PRIVILEGES ON api_key_service.* TO 'game_app'@'%';
CREATE DATABASE IF NOT EXISTS version_service;
CREATE DATABASE IF NOT EXISTS build_service;
CREATE DATABASE IF NOT EXISTS release_service;
CREATE DATABASE IF NOT EXISTS deployment_service;
GRANT ALL PRIVILEGES ON version_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON build_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON release_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON deployment_service.* TO 'game_app'@'%';
CREATE DATABASE IF NOT EXISTS contract_service;
CREATE DATABASE IF NOT EXISTS revenue_service;
CREATE DATABASE IF NOT EXISTS ledger_service;
CREATE DATABASE IF NOT EXISTS billing_service;
CREATE DATABASE IF NOT EXISTS webhook_service;
GRANT ALL PRIVILEGES ON contract_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON revenue_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON ledger_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON billing_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON webhook_service.* TO 'game_app'@'%';
CREATE DATABASE IF NOT EXISTS audit_service;
CREATE DATABASE IF NOT EXISTS incident_service;
CREATE DATABASE IF NOT EXISTS feature_flag_service;
GRANT ALL PRIVILEGES ON audit_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON incident_service.* TO 'game_app'@'%';
GRANT ALL PRIVILEGES ON feature_flag_service.* TO 'game_app'@'%';
CREATE DATABASE IF NOT EXISTS analytics_service;
GRANT ALL PRIVILEGES ON analytics_service.* TO 'game_app'@'%';
FLUSH PRIVILEGES;


