spring.application.name=spring-service-template
platform.core.service-name=${spring.application.name}
platform.core.api-version=v1
logging.pattern.level=%5p [requestId=%X{requestId:-}, correlationId=%X{correlationId:-}]
