package com.gameaggregator.tenantservice.application;
import static com.gameaggregator.tenantservice.api.TenantDtos.*; import com.gameaggregator.tenantservice.domain.*; import com.gameaggregator.tenantservice.infrastructure.*; import com.gameaggregator.platform.core.common.exception.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class TenantService { private final TenantRepository tenants; private final OrganizationRepository organizations; private final TenantMemberRepository members; private final RoleRepository roles; private final PermissionRepository permissions; private final MemberRoleRepository memberRoles; public TenantService(TenantRepository a,OrganizationRepository b,TenantMemberRepository c,RoleRepository d,PermissionRepository e,MemberRoleRepository f){tenants=a;organizations=b;members=c;roles=d;permissions=e;memberRoles=f;}
 public TenantView create(UUID owner,CreateTenant r){if(tenants.existsBySlug(r.slug()))throw new DomainException("TENANT_EXISTS","Tenant slug already exists",HttpStatus.CONFLICT);Tenant t=tenants.save(new Tenant(r.slug(),r.name()));TenantMember m=members.save(new TenantMember(t.getId(),owner));Role admin=new Role(t.getId(),"TENANT_ADMIN","Tenant Administrator");permissions.findAll().forEach(admin::addPermission);roles.save(admin);memberRoles.save(new MemberRole(m.getId(),admin.getId()));return view(t);}
 public OrganizationView organization(UUID user,UUID tenantId,CreateOrganization r){requireMember(tenantId,user);Organization o=organizations.save(new Organization(tenantId,r.slug(),r.name(),r.type().toUpperCase()));return new OrganizationView(o.getId(),o.getTenantId(),o.getSlug(),o.getName(),o.getType());}
 public MemberView addMember(UUID actor,UUID tenantId,AddMember r){requirePermission(actor,tenantId,"tenant:member:create");TenantMember m=members.findByTenantIdAndUserId(tenantId,r.userId()).orElseGet(()->members.save(new TenantMember(tenantId,r.userId())));return new MemberView(m.getId(),m.getTenantId(),m.getUserId(),m.getStatus());}
 public RoleView createRole(UUID actor,UUID tenantId,CreateRole r){requirePermission(actor,tenantId,"tenant:role:manage");Role role=new Role(tenantId,r.code(),r.name());if(r.permissions()!=null)r.permissions().forEach(code->role.addPermission(permissions.findByCode(code).orElseThrow(()->new NotFoundException("PERMISSION_NOT_FOUND","Permission not found: "+code))));roles.save(role);return roleView(role);}
 public void assignRole(UUID actor,UUID tenantId,UUID memberId,UUID roleId){requirePermission(actor,tenantId,"tenant:role:manage");TenantMember member=members.findById(memberId).filter(m->m.getTenantId().equals(tenantId)).orElseThrow(()->new NotFoundException("MEMBER_NOT_FOUND","Member was not found"));Role role=roles.findById(roleId).filter(x->x.getTenantId().equals(tenantId)).orElseThrow(()->new NotFoundException("ROLE_NOT_FOUND","Role was not found"));memberRoles.save(new MemberRole(member.getId(),role.getId()));}
 @Transactional(readOnly=true) public AccessContext access(UUID user,UUID tenantId){TenantMember member=requireMember(tenantId,user);Set<String> roleCodes=new HashSet<>();Set<String> permissionCodes=new HashSet<>();for(MemberRole mr:memberRoles.findByMemberId(member.getId()))roles.findById(mr.getRoleId()).ifPresent(role->{roleCodes.add(role.getCode());role.getPermissions().forEach(p->permissionCodes.add(p.getCode()));});return new AccessContext(user,tenantId,Set.copyOf(roleCodes),Set.copyOf(permissionCodes));}
 private TenantMember requireMember(UUID tenantId,UUID user){return members.findByTenantIdAndUserId(tenantId,user).filter(m->"ACTIVE".equals(m.getStatus())).orElseThrow(()->new DomainException("TENANT_ACCESS_DENIED","User is not an active tenant member",HttpStatus.FORBIDDEN));} private void requirePermission(UUID user,UUID tenant,String permission){if(!access(user,tenant).currentPermissions().contains(permission))throw new DomainException("PERMISSION_DENIED","Required permission: "+permission,HttpStatus.FORBIDDEN);} private TenantView view(Tenant t){return new TenantView(t.getId(),t.getSlug(),t.getName(),t.getStatus());} private RoleView roleView(Role r){Set<String> p=new HashSet<>();r.getPermissions().forEach(x->p.add(x.getCode()));return new RoleView(r.getId(),r.getCode(),r.getName(),Set.copyOf(p));}}
