"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Bell, Check, ChevronDown, ChevronsLeft, Command, Gamepad2, LogOut, Menu, Search, Settings, User, X } from "lucide-react";
import { Button, cn } from "./primitives";

export interface ShellNavigationItem { label: string; href: string; icon: ReactNode; badge?: string; active?: boolean; permission?: string; }
export interface AppShellProps { children: ReactNode; portalLabel: string; navigation: ShellNavigationItem[]; user?: { name: string; email: string; initials: string }; tenants?: string[]; environments?: string[]; }
export function AppShell({ children, portalLabel, navigation, user = { name: "Alex Morgan", email: "alex@gameaggregator.dev", initials: "AM" }, tenants = ["Northwind Games", "Atlas Publishing"], environments = ["Production", "Sandbox"] }: AppShellProps) {
 const [mobileOpen,setMobileOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[commandOpen,setCommandOpen]=useState(false),[notificationsOpen,setNotificationsOpen]=useState(false),[userOpen,setUserOpen]=useState(false); const [query,setQuery]=useState(""),[tenant,setTenant]=useState(tenants[0]),[environment,setEnvironment]=useState(environments[0]);
 useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setCommandOpen(v=>!v);}if(event.key==="Escape"){setCommandOpen(false);setMobileOpen(false);setNotificationsOpen(false);}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);},[]);
 const filtered=useMemo(()=>navigation.filter(item=>item.label.toLowerCase().includes(query.toLowerCase())),[navigation,query]);
 return <div className="min-h-dvh bg-[var(--ga-background)] text-[var(--ga-foreground)]"><aside className={cn("fixed inset-y-0 left-0 z-40 hidden border-r border-white/10 bg-[#071a17] text-white transition-[width] duration-200 lg:flex lg:flex-col",collapsed?"w-[5.25rem]":"w-64")}><SidebarContent collapsed={collapsed} portalLabel={portalLabel} navigation={navigation}/><button className="m-4 mt-auto flex h-9 items-center justify-center gap-2 rounded-lg border border-white/10 text-xs text-white/60 hover:bg-white/10 hover:text-white" onClick={()=>setCollapsed(v=>!v)} aria-label="Toggle sidebar"><ChevronsLeft className={cn("size-4 transition-transform",collapsed&&"rotate-180")}/>{!collapsed&&"Collapse sidebar"}</button></aside>
 {mobileOpen&&<><button aria-label="Close navigation" className="fixed inset-0 z-40 bg-slate-950/45 backdrop-blur-sm lg:hidden" onClick={()=>setMobileOpen(false)}/><aside className="fixed inset-y-0 left-0 z-50 flex w-[min(21rem,88vw)] flex-col bg-[#071a17] text-white shadow-2xl lg:hidden"><button aria-label="Close navigation" className="absolute right-3 top-3 grid size-9 place-items-center rounded-lg text-white/70 hover:bg-white/10" onClick={()=>setMobileOpen(false)}><X className="size-5"/></button><SidebarContent portalLabel={portalLabel} navigation={navigation}/></aside></>}
 <div className={cn("transition-[padding] duration-200",collapsed?"lg:pl-[5.25rem]":"lg:pl-64")}><header className="sticky top-0 z-30 border-b border-[var(--ga-border)] bg-[var(--ga-surface)]/95 backdrop-blur-xl"><div className="flex h-16 items-center gap-2 px-4 sm:px-6 lg:px-8"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobileOpen(true)} aria-label="Open navigation"><Menu className="size-5"/></Button><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-medium uppercase tracking-[.14em] text-[var(--ga-muted-foreground)]">Workspace / Overview</p><h1 className="truncate text-sm font-semibold sm:text-base">Operations overview</h1></div><button onClick={()=>setCommandOpen(true)} className="hidden h-9 w-52 items-center gap-2 rounded-lg border border-[var(--ga-border)] bg-[var(--ga-surface-muted)] px-3 text-xs text-[var(--ga-muted-foreground)] hover:border-[var(--ga-ring)] md:flex"><Search className="size-3.5"/>Search anything<span className="ml-auto rounded border border-[var(--ga-border)] bg-[var(--ga-surface)] px-1.5 py-0.5 font-mono">âŒ˜K</span></button><select aria-label="Tenant" value={tenant} onChange={e=>setTenant(e.target.value)} className="hidden h-9 max-w-40 rounded-lg border border-[var(--ga-border)] bg-[var(--ga-surface)] px-2 text-xs xl:block">{tenants.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Environment" value={environment} onChange={e=>setEnvironment(e.target.value)} className="hidden h-9 rounded-lg border border-[var(--ga-border)] bg-[var(--ga-surface)] px-2 text-xs sm:block">{environments.map(value=><option key={value}>{value}</option>)}</select><Button variant="ghost" size="icon" className="relative" onClick={()=>setNotificationsOpen(true)} aria-label="Notifications"><Bell className="size-4"/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-rose-500"/></Button><div className="relative"><button onClick={()=>setUserOpen(v=>!v)} className="flex items-center gap-2 rounded-xl p-1 hover:bg-[var(--ga-surface-muted)]"><span className="grid size-8 place-items-center rounded-lg bg-[#0b725c] text-xs font-semibold text-white">{user.initials}</span><ChevronDown className="hidden size-3.5 sm:block"/></button>{userOpen&&<UserMenu user={user}/>}</div></div><div className="flex gap-2 overflow-x-auto border-t border-[var(--ga-border)] px-4 py-2 sm:hidden"><MiniSelect value={tenant} values={tenants} onChange={setTenant}/><MiniSelect value={environment} values={environments} onChange={setEnvironment}/></div></header><main className="mx-auto w-full max-w-[1600px] p-4 sm:p-6 lg:p-8">{children}</main></div>
 {commandOpen&&<CommandPalette query={query} setQuery={setQuery} items={filtered} close={()=>setCommandOpen(false)}/>} {notificationsOpen&&<NotificationPanel close={()=>setNotificationsOpen(false)}/>}</div>;
}
function SidebarContent({portalLabel,navigation,collapsed=false}:{portalLabel:string;navigation:ShellNavigationItem[];collapsed?:boolean}){return <><div className="flex h-20 items-center gap-3 border-b border-white/10 px-5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-400 text-[#06231d]"><Gamepad2 className="size-5"/></span>{!collapsed&&<div className="min-w-0"><p className="font-semibold tracking-tight">Game Aggregator</p><p className="truncate text-xs text-white/50">{portalLabel}</p></div>}</div><nav className="grid gap-1 overflow-y-auto p-3" aria-label="Main navigation">{navigation.map(item=><a key={item.label} href={item.href} title={collapsed?item.label:undefined} className={cn("flex h-10 items-center gap-3 rounded-xl px-3 text-sm text-white/65 transition hover:bg-white/10 hover:text-white",item.active&&"bg-emerald-400/15 text-emerald-200")}>{item.icon}{!collapsed&&<><span className="truncate">{item.label}</span>{item.badge&&<span className="ml-auto rounded-full bg-white/10 px-2 py-0.5 text-[10px]">{item.badge}</span>}</>}</a>)}</nav></>}
function MiniSelect({value,values,onChange}:{value:string;values:string[];onChange:(v:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)} className="h-8 min-w-36 rounded-lg border border-[var(--ga-border)] bg-[var(--ga-surface)] px-2 text-xs">{values.map(v=><option key={v}>{v}</option>)}</select>}
function UserMenu({user}:{user:{name:string;email:string;initials:string}}){return <div className="absolute right-0 top-11 z-50 w-64 rounded-2xl border border-[var(--ga-border)] bg-[var(--ga-surface)] p-2 shadow-xl"><div className="border-b border-[var(--ga-border)] px-3 py-2"><p className="text-sm font-semibold">{user.name}</p><p className="truncate text-xs text-[var(--ga-muted-foreground)]">{user.email}</p></div><MenuLink icon={<User/>} label="Profile"/><MenuLink icon={<Settings/>} label="Account settings"/><MenuLink icon={<LogOut/>} label="Sign out" danger onClick={()=>{sessionStorage.removeItem("ga_access_token");sessionStorage.removeItem("ga_refresh_token");window.location.assign("/login");}}/></div>}
function MenuLink({icon,label,danger=false,onClick}:{icon:ReactNode;label:string;danger?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={cn("flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-[var(--ga-surface-muted)] [&_svg]:size-4",danger&&"text-rose-600")}>{icon}{label}</button>}
function CommandPalette({query,setQuery,items,close}:{query:string;setQuery:(v:string)=>void;items:ShellNavigationItem[];close:()=>void}){return <div className="fixed inset-0 z-[70] flex justify-center bg-slate-950/50 px-4 pt-[12vh] backdrop-blur-sm" onMouseDown={close}><section role="dialog" aria-modal="true" aria-label="Command palette" onMouseDown={e=>e.stopPropagation()} className="h-fit w-full max-w-xl overflow-hidden rounded-2xl border border-white/10 bg-[var(--ga-surface)] shadow-2xl"><div className="flex items-center gap-3 border-b border-[var(--ga-border)] px-4"><Search className="size-5 text-[var(--ga-muted-foreground)]"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pages and actions..." className="h-14 flex-1 bg-transparent text-sm outline-none"/><button onClick={close} className="text-xs text-[var(--ga-muted-foreground)]">ESC</button></div><div className="max-h-80 overflow-y-auto p-2">{items.map(item=><a href={item.href} key={item.label} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm hover:bg-[var(--ga-surface-muted)] [&_svg]:size-4">{item.icon}{item.label}<Command className="ml-auto text-[var(--ga-muted-foreground)]"/></a>)}{!items.length&&<p className="p-8 text-center text-sm text-[var(--ga-muted-foreground)]">No matching pages</p>}</div></section></div>}
function NotificationPanel({close}:{close:()=>void}){const notes=[{title:"Release deployed",body:"Game SDK 2.8.0 is live in production.",time:"2m"},{title:"Permission request",body:"Mina requested release:approve access.",time:"18m"},{title:"Incident acknowledged",body:"API latency is back within target.",time:"1h"}];return <><button aria-label="Close notifications" className="fixed inset-0 z-50 bg-slate-950/30" onClick={close}/><aside className="fixed inset-y-0 right-0 z-[60] w-full max-w-sm bg-[var(--ga-surface)] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-lg font-semibold">Notifications</p><p className="text-xs text-[var(--ga-muted-foreground)]">Latest workspace activity</p></div><Button variant="ghost" size="icon" onClick={close}><X className="size-5"/></Button></div><div className="mt-6 grid gap-3">{notes.map(note=><div key={note.title} className="rounded-2xl border border-[var(--ga-border)] p-4"><div className="flex items-start gap-3"><span className="mt-0.5 grid size-7 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check className="size-4"/></span><div><p className="text-sm font-semibold">{note.title}</p><p className="mt-1 text-xs leading-5 text-[var(--ga-muted-foreground)]">{note.body}</p></div><span className="ml-auto text-[10px] text-[var(--ga-muted-foreground)]">{note.time}</span></div></div>)}</div></aside></>}